urls:
  zk-url: 192.168.1.12
spring:
  application:
    name: nvwa-openapi-service
  redis:
    url: ${urls.zk-url}
    port: 6379
server:
  port: 8088

# dubbo 配置
dubbo:
  application:
    name: openapi-service-consumer
  scan:
    base-packages: cn.home.jeffrey.api.open
  registry:
    address: zookeeper://${urls.zk-url}:2181
  consumer:
    check: false
    retries: 0
    timeout: 50000
